### ISSUE TITLE
Question: Why do box the value?

### ISSUE THREAD

**Issue by msevestre** [Andarist/use-constant#5]
Hey @Andarist 

A quick question for you. I am wondering why you do not save the props directly as current

e.g.
```
export default function useConstant<T>(fn: () => T): T {
  const ref = React.useRef<T>()

  if (!ref.current) {
    ref.current = fn()
  }

  return ref.current
}

```

I am just curious :). 

Cheers

**Comment by twgraham** [comment]
I assume its because if your function resolves to something falsey e.g. an empty string, then it won't continue trying to resolve it on subsequent function calls (and hence undermine the entire point of useConstant).

**Comment by Andarist** [comment]
Thank you @twgraham for answering - yes, that's exactly why this is boxed. I want to be sure that the input function evaluates just once.

**Comment by hardfist** [comment]
sorry to bother, but why not just
```ts
export  function useConstant<T>(fn: () => T): T {
  const ref = React.useRef(fn());
  return ref.current;
}
```
what's the difference ?
